#!/usr/bin/env node
// Syncs compiled contract ABIs + latest local-anvil deployment addresses
// from contracts/ into iceburg-ui/src/contracts, so the frontend always
// has an up-to-date, typed view of the contracts without any manual copy/paste.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(fileURLToPath(import.meta.url));
const contractsDir = path.join(root, "..", "contracts");
const uiOutDir = path.join(root, "..", "iceburg-ui", "src", "contracts");

// Add every contract you want mirrored to the frontend here, e.g.:
// { name: "Issuance", broadcastScript: "Issuance.s.sol" }
const CONTRACTS = [];

const ANVIL_CHAIN_ID = "31337";

mkdirSync(uiOutDir, { recursive: true });

const exports = [];

for (const { name, broadcastScript } of CONTRACTS) {
  const artifactPath = path.join(contractsDir, "out", `${name}.sol`, `${name}.json`);
  if (!existsSync(artifactPath)) {
    console.warn(`[sync-abi] skipping ${name}: no build artifact at ${artifactPath}. Run "forge build" first.`);
    continue;
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf-8"));
  const abi = artifact.abi;

  const broadcastPath = path.join(
    contractsDir,
    "broadcast",
    broadcastScript,
    ANVIL_CHAIN_ID,
    "run-latest.json"
  );

  let address = null;
  if (existsSync(broadcastPath)) {
    const broadcast = JSON.parse(readFileSync(broadcastPath, "utf-8"));
    const creation = broadcast.transactions.find(
      (tx) => tx.transactionType === "CREATE" && tx.contractName === name
    );
    address = creation?.contractAddress ?? null;
  } else {
    console.warn(`[sync-abi] no local deployment found for ${name} yet. Run "make deploy-local" in contracts/.`);
  }

  const fileContent = `// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit by hand.
// Regenerate with \`make sync-abi\` (or \`make deploy-local\`) from contracts/.

export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;

export const ${name}Address = ${address ? `"${address}"` : "undefined"} as \`0x\${string}\` | undefined;
`;

  writeFileSync(path.join(uiOutDir, `${name}.ts`), fileContent);
  exports.push(name);
  console.log(`[sync-abi] wrote ${name}.ts${address ? ` (address ${address})` : " (no address yet)"}`);
}

const indexContent = exports
  .map((name) => `export { ${name}Abi, ${name}Address } from "./${name}";`)
  .join("\n");
writeFileSync(path.join(uiOutDir, "index.ts"), indexContent + "\n");
