#!/usr/bin/env node
// Syncs compiled contract ABIs + deployed addresses (across every chain a
// contract has actually been deployed to) from contracts/ into
// iceburg-ui/src/contracts, so the frontend always has an up-to-date,
// typed view of the contracts without any manual copy/paste.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(fileURLToPath(import.meta.url));
const contractsDir = path.join(root, "..", "contracts");
const uiOutDir = path.join(root, "..", "iceburg-ui", "src", "contracts");

const CONTRACTS = [
  { name: "DemoUSD", broadcastScript: "DeployDemoPaymentToken.s.sol" },
  { name: "AttestorRegistry", broadcastScript: "DeployAttestorRegistry.s.sol" },
  { name: "IssuanceFactory", broadcastScript: "DeployIssuanceFactory.s.sol" },
  { name: "SecurityToken", deployed: false },
  { name: "Issuance", deployed: false },
];

mkdirSync(uiOutDir, { recursive: true });

function addressesByChain(broadcastScript, name) {
  const scriptDir = path.join(contractsDir, "broadcast", broadcastScript);
  const addresses = {};
  if (!existsSync(scriptDir)) return addresses;

  for (const entry of readdirSync(scriptDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || !/^\d+$/.test(entry.name)) continue;
    const runLatestPath = path.join(scriptDir, entry.name, "run-latest.json");
    if (!existsSync(runLatestPath)) continue;

    const broadcast = JSON.parse(readFileSync(runLatestPath, "utf-8"));
    const creation = broadcast.transactions.find(
      (tx) => tx.transactionType === "CREATE" && tx.contractName === name
    );
    if (creation?.contractAddress) addresses[entry.name] = creation.contractAddress;
  }
  return addresses;
}

const exports = [];

for (const { name, broadcastScript, deployed = true } of CONTRACTS) {
  const artifactPath = path.join(contractsDir, "out", `${name}.sol`, `${name}.json`);
  if (!existsSync(artifactPath)) {
    console.warn(`[sync-abi] skipping ${name}: no build artifact at ${artifactPath}. Run "forge build" first.`);
    continue;
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf-8"));
  const abi = artifact.abi;

  const byChain = deployed ? addressesByChain(broadcastScript, name) : {};

  const fileContent = `// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit by hand.
// Regenerate with \`make sync-abi\` (or \`make deploy-local\`) from contracts/.

export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;

export const ${name}AddressByChain: Record<number, \`0x\${string}\`> = ${JSON.stringify(byChain, null, 2)};
`;

  writeFileSync(path.join(uiOutDir, `${name}.ts`), fileContent);
  exports.push(name);

  const chainCount = Object.keys(byChain).length;
  const addressNote = chainCount
    ? ` (${chainCount} chain${chainCount === 1 ? "" : "s"}: ${Object.keys(byChain).join(", ")})`
    : deployed
      ? " (no deployment found on any chain yet)"
      : " (no single address — read the real one from a live createIssuance receipt)";
  console.log(`[sync-abi] wrote ${name}.ts${addressNote}`);
}

const indexContent = exports
  .map((name) => `export { ${name}Abi, ${name}AddressByChain } from "./${name}";`)
  .concat('export { useContractAddress } from "./useContractAddress";')
  .join("\n");
writeFileSync(path.join(uiOutDir, "index.ts"), indexContent + "\n");
