// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit by hand.
// Regenerate with `make sync-abi` (or `make deploy-local`) from contracts/.

export const IssuanceFactoryAbi = [
  {
    "type": "function",
    "name": "createIssuance",
    "inputs": [
      {
        "name": "params_",
        "type": "tuple",
        "internalType": "struct Issuance.IssuanceParams",
        "components": [
          {
            "name": "supply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "reservePrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "capBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minHolders",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "minBond",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "paymentToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "securityToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "approvedAttestors",
            "type": "address[]",
            "internalType": "address[]"
          },
          {
            "name": "commitWindowEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "revealWindowEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "challengeWindowLength",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenName",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "tokenSymbol",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "issuance",
        "type": "address",
        "internalType": "contract Issuance"
      },
      {
        "name": "securityToken",
        "type": "address",
        "internalType": "contract SecurityToken"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "IssuanceCreated",
    "inputs": [
      {
        "name": "issuance",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "securityToken",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "issuer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenName",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "tokenSymbol",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  }
] as const;

export const IssuanceFactoryAddressByChain: Record<number, `0x${string}`> = {
  "31337": "0x0dcd1bf9a1b36ce34237eeafef220932846bcd82",
  "46630": "0xa7ea9080a745da1d5334e99c2f899400c58bf974"
};
