name: Deploy

on:
  push:
    tags:
      - "v*.*.*"
      - "!v*.*.*-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iceburg-ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: iceburg-ui/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
      - run: npm i -g vercel@latest
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_ICEBURG_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: ./deploy.sh
